{% set name = "tango-atk-panel" %}
{% set version = "6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/atk-panel/-/archive/{{ version }}/atk-panel-{{ version }}.tar.gz
  sha256: b7eebc2b015cc0a67e701061e3d4e72c437533a50b2143a32678484d81c2c305

build:
  number: 0

requirements:
  build:
    - openjdk 8
    - maven
  run:
    - openjdk >=8
    - jtango >=9.6.8,<10.0.0
    - tango-atk >=9.3.22

test:
  commands:
    - test -f ${PREFIX}/share/java/ATKPanel.jar                  # [unix]
    - test -f ${PREFIX}/share/java/ATKPanel-${PKG_VERSION}.jar   # [unix]
    - test -f ${PREFIX}/bin/atkpanel                             # [unix]
    - if not exist %PREFIX%\share\java\ATKPanel.jar exit 1       # [win]
    - if not exist %PREFIX%\Scripts\atkpanel.bat exit 1          # [win]

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Generic control panel application for Tango
  description: |
    AtkPanel is a generic control panel application.
    It can be used to control any Tango device.
    Tango-Controls is a software toolkit for building control systems.
  dev_url: https://gitlab.com/tango-controls/atk-panel
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/atkpanel/atkpanel.html

extra:
  recipe-maintainers:
    - beenje
